<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubCountiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sub_counties')->insert(array(
            array('id' => '1','county_id' => '2','sub_county_name' => 'changamwe'),
            array('id' => '2','county_id' => '2','sub_county_name' => 'jomvu'),
            array('id' => '3','county_id' => '2','sub_county_name' => 'kisauni'),
            array('id' => '4','county_id' => '2','sub_county_name' => 'nyali'),
            array('id' => '5','county_id' => '2','sub_county_name' => 'likoni'),
            array('id' => '6','county_id' => '2','sub_county_name' => 'mvita'),
            array('id' => '7','county_id' => '20','sub_county_name' => 'msambweni'),
            array('id' => '8','county_id' => '20','sub_county_name' => 'lungalunga'),
            array('id' => '9','county_id' => '20','sub_county_name' => 'matuga'),
            array('id' => '10','county_id' => '20','sub_county_name' => 'kinango'),
            array('id' => '11','county_id' => '16','sub_county_name' => 'kilifi north'),
            array('id' => '12','county_id' => '16','sub_county_name' => 'kilifi south'),
            array('id' => '13','county_id' => '16','sub_county_name' => 'kaloleni'),
            array('id' => '14','county_id' => '16','sub_county_name' => 'rabai'),
            array('id' => '15','county_id' => '16','sub_county_name' => 'ganze'),
            array('id' => '16','county_id' => '16','sub_county_name' => 'malindi'),
            array('id' => '17','county_id' => '16','sub_county_name' => 'magarini'),
            array('id' => '18','county_id' => '39','sub_county_name' => 'garsen'),
            array('id' => '19','county_id' => '39','sub_county_name' => 'galole'),
            array('id' => '20','county_id' => '39','sub_county_name' => 'bura'),
            array('id' => '21','county_id' => '22','sub_county_name' => 'lamu east'),
            array('id' => '22','county_id' => '22','sub_county_name' => 'lamu west'),
            array('id' => '23','county_id' => '38','sub_county_name' => 'taveta'),
            array('id' => '24','county_id' => '38','sub_county_name' => 'wundanyi'),
            array('id' => '25','county_id' => '38','sub_county_name' => 'mwatate'),
            array('id' => '26','county_id' => '38','sub_county_name' => 'voi'),
            array('id' => '27','county_id' => '9','sub_county_name' => 'garissa township'),
            array('id' => '28','county_id' => '9','sub_county_name' => 'balambala'),
            array('id' => '29','county_id' => '9','sub_county_name' => 'lagdera'),
            array('id' => '30','county_id' => '9','sub_county_name' => 'dadaab'),
            array('id' => '31','county_id' => '9','sub_county_name' => 'fafi'),
            array('id' => '32','county_id' => '9','sub_county_name' => 'ijara'),
            array('id' => '33','county_id' => '45','sub_county_name' => 'wajir north'),
            array('id' => '34','county_id' => '45','sub_county_name' => 'wajir east'),
            array('id' => '35','county_id' => '45','sub_county_name' => 'tarbaj'),
            array('id' => '36','county_id' => '45','sub_county_name' => 'wajir west'),
            array('id' => '37','county_id' => '45','sub_county_name' => 'eldas'),
            array('id' => '38','county_id' => '45','sub_county_name' => 'wajir south'),
            array('id' => '39','county_id' => '24','sub_county_name' => 'mandera west'),
            array('id' => '40','county_id' => '24','sub_county_name' => 'banissa'),
            array('id' => '41','county_id' => '24','sub_county_name' => 'mandera north'),
            array('id' => '42','county_id' => '24','sub_county_name' => 'mandera south'),
            array('id' => '43','county_id' => '24','sub_county_name' => 'mandera east'),
            array('id' => '44','county_id' => '24','sub_county_name' => 'lafey'),
            array('id' => '45','county_id' => '25','sub_county_name' => 'moyale'),
            array('id' => '46','county_id' => '25','sub_county_name' => 'north horr'),
            array('id' => '47','county_id' => '25','sub_county_name' => 'saku'),
            array('id' => '48','county_id' => '25','sub_county_name' => 'laisamis'),
            array('id' => '49','county_id' => '11','sub_county_name' => 'isiolo north'),
            array('id' => '50','county_id' => '11','sub_county_name' => 'isiolo south'),
            array('id' => '51','county_id' => '26','sub_county_name' => 'igembe south'),
            array('id' => '52','county_id' => '26','sub_county_name' => 'igembe central'),
            array('id' => '53','county_id' => '26','sub_county_name' => 'igembe north'),
            array('id' => '54','county_id' => '26','sub_county_name' => 'tigania west'),
            array('id' => '55','county_id' => '26','sub_county_name' => 'tigania east'),
            array('id' => '56','county_id' => '26','sub_county_name' => 'north imenti'),
            array('id' => '57','county_id' => '26','sub_county_name' => 'buuri'),
            array('id' => '58','county_id' => '26','sub_county_name' => 'central imenti'),
            array('id' => '59','county_id' => '26','sub_county_name' => 'south imenti'),
            array('id' => '60','county_id' => '40','sub_county_name' => 'maara'),
            array('id' => '61','county_id' => '40','sub_county_name' => 'chuka/igambang\'om'),
            array('id' => '62','county_id' => '40','sub_county_name' => 'tharaka'),
            array('id' => '63','county_id' => '8','sub_county_name' => 'manyatta'),
            array('id' => '64','county_id' => '8','sub_county_name' => 'runyenjes'),
            array('id' => '65','county_id' => '8','sub_county_name' => 'mbeere south'),
            array('id' => '66','county_id' => '8','sub_county_name' => 'mbeere north'),
            array('id' => '67','county_id' => '19','sub_county_name' => 'mwingi north'),
            array('id' => '68','county_id' => '19','sub_county_name' => 'mwingi west'),
            array('id' => '69','county_id' => '19','sub_county_name' => 'mwingi central'),
            array('id' => '70','county_id' => '19','sub_county_name' => 'kitui west'),
            array('id' => '71','county_id' => '19','sub_county_name' => 'kitui rural'),
            array('id' => '72','county_id' => '19','sub_county_name' => 'kitui central'),
            array('id' => '73','county_id' => '19','sub_county_name' => 'kitui east'),
            array('id' => '74','county_id' => '19','sub_county_name' => 'kitui south'),
            array('id' => '75','county_id' => '28','sub_county_name' => 'masinga'),
            array('id' => '76','county_id' => '28','sub_county_name' => 'yatta'),
            array('id' => '77','county_id' => '28','sub_county_name' => 'kangundo'),
            array('id' => '78','county_id' => '28','sub_county_name' => 'matungulu'),
            array('id' => '79','county_id' => '28','sub_county_name' => 'kathiani'),
            array('id' => '80','county_id' => '28','sub_county_name' => 'mavoko'),
            array('id' => '81','county_id' => '28','sub_county_name' => 'machakos town'),
            array('id' => '82','county_id' => '28','sub_county_name' => 'mwala'),
            array('id' => '83','county_id' => '23','sub_county_name' => 'mbooni'),
            array('id' => '84','county_id' => '23','sub_county_name' => 'kilome'),
            array('id' => '85','county_id' => '23','sub_county_name' => 'kaiti'),
            array('id' => '86','county_id' => '23','sub_county_name' => 'makueni'),
            array('id' => '87','county_id' => '23','sub_county_name' => 'kibwezi west'),
            array('id' => '88','county_id' => '23','sub_county_name' => 'kibwezi east'),
            array('id' => '89','county_id' => '34','sub_county_name' => 'kinangop'),
            array('id' => '90','county_id' => '34','sub_county_name' => 'kipipiri'),
            array('id' => '91','county_id' => '34','sub_county_name' => 'ol kalou'),
            array('id' => '92','county_id' => '34','sub_county_name' => 'ol jorok'),
            array('id' => '93','county_id' => '34','sub_county_name' => 'ndaragwa'),
            array('id' => '94','county_id' => '35','sub_county_name' => 'tetu'),
            array('id' => '95','county_id' => '35','sub_county_name' => 'kieni'),
            array('id' => '96','county_id' => '35','sub_county_name' => 'mathira'),
            array('id' => '97','county_id' => '35','sub_county_name' => 'othaya'),
            array('id' => '98','county_id' => '35','sub_county_name' => 'mukurweini'),
            array('id' => '99','county_id' => '35','sub_county_name' => 'nyeri town'),
            array('id' => '100','county_id' => '17','sub_county_name' => 'mwea'),
            array('id' => '101','county_id' => '17','sub_county_name' => 'gichugu'),
            array('id' => '102','county_id' => '17','sub_county_name' => 'ndia'),
            array('id' => '103','county_id' => '17','sub_county_name' => 'kirinyaga central'),
            array('id' => '104','county_id' => '29','sub_county_name' => 'kangema'),
            array('id' => '105','county_id' => '29','sub_county_name' => 'mathioya'),
            array('id' => '106','county_id' => '29','sub_county_name' => 'kiharu'),
            array('id' => '107','county_id' => '29','sub_county_name' => 'kigumo'),
            array('id' => '108','county_id' => '29','sub_county_name' => 'maragwa'),
            array('id' => '109','county_id' => '29','sub_county_name' => 'kandara'),
            array('id' => '110','county_id' => '29','sub_county_name' => 'gatanga'),
            array('id' => '111','county_id' => '15','sub_county_name' => 'gatundu south'),
            array('id' => '112','county_id' => '15','sub_county_name' => 'gatundu north'),
            array('id' => '113','county_id' => '15','sub_county_name' => 'juja'),
            array('id' => '114','county_id' => '15','sub_county_name' => 'thika town'),
            array('id' => '115','county_id' => '15','sub_county_name' => 'ruiru'),
            array('id' => '116','county_id' => '15','sub_county_name' => 'githunguri'),
            array('id' => '117','county_id' => '15','sub_county_name' => 'kiambu'),
            array('id' => '118','county_id' => '15','sub_county_name' => 'kiambaa'),
            array('id' => '119','county_id' => '15','sub_county_name' => 'kabete'),
            array('id' => '120','county_id' => '15','sub_county_name' => 'kikuyu'),
            array('id' => '121','county_id' => '15','sub_county_name' => 'limuru'),
            array('id' => '122','county_id' => '15','sub_county_name' => 'lari'),
            array('id' => '123','county_id' => '42','sub_county_name' => 'turkana north'),
            array('id' => '124','county_id' => '42','sub_county_name' => 'turkana west'),
            array('id' => '125','county_id' => '42','sub_county_name' => 'turkana central'),
            array('id' => '126','county_id' => '42','sub_county_name' => 'loima'),
            array('id' => '127','county_id' => '42','sub_county_name' => 'turkana south'),
            array('id' => '128','county_id' => '42','sub_county_name' => 'turkana east'),
            array('id' => '129','county_id' => '46','sub_county_name' => 'kapenguria'),
            array('id' => '130','county_id' => '46','sub_county_name' => 'sigor'),
            array('id' => '131','county_id' => '46','sub_county_name' => 'kacheliba'),
            array('id' => '132','county_id' => '46','sub_county_name' => 'pokot south'),
            array('id' => '133','county_id' => '36','sub_county_name' => 'samburu west'),
            array('id' => '134','county_id' => '36','sub_county_name' => 'samburu north'),
            array('id' => '135','county_id' => '36','sub_county_name' => 'samburu east'),
            array('id' => '136','county_id' => '41','sub_county_name' => 'kwanza'),
            array('id' => '137','county_id' => '41','sub_county_name' => 'endebess'),
            array('id' => '138','county_id' => '41','sub_county_name' => 'saboti'),
            array('id' => '139','county_id' => '41','sub_county_name' => 'kiminini'),
            array('id' => '140','county_id' => '41','sub_county_name' => 'cherangany'),
            array('id' => '141','county_id' => '43','sub_county_name' => 'soy'),
            array('id' => '142','county_id' => '43','sub_county_name' => 'turbo'),
            array('id' => '143','county_id' => '43','sub_county_name' => 'moiben'),
            array('id' => '144','county_id' => '43','sub_county_name' => 'ainabkoi'),
            array('id' => '145','county_id' => '43','sub_county_name' => 'kapseret'),
            array('id' => '146','county_id' => '43','sub_county_name' => 'kesses'),
            array('id' => '147','county_id' => '7','sub_county_name' => 'marakwet east'),
            array('id' => '148','county_id' => '7','sub_county_name' => 'marakwet west'),
            array('id' => '149','county_id' => '7','sub_county_name' => 'keiyo north'),
            array('id' => '150','county_id' => '7','sub_county_name' => 'keiyo south'),
            array('id' => '151','county_id' => '31','sub_county_name' => 'tinderet'),
            array('id' => '152','county_id' => '31','sub_county_name' => 'aldai'),
            array('id' => '153','county_id' => '31','sub_county_name' => 'nandi hills'),
            array('id' => '154','county_id' => '31','sub_county_name' => 'chesumei'),
            array('id' => '155','county_id' => '31','sub_county_name' => 'emgwen'),
            array('id' => '156','county_id' => '31','sub_county_name' => 'mosop'),
            array('id' => '157','county_id' => '47','sub_county_name' => 'tiaty'),
            array('id' => '158','county_id' => '47','sub_county_name' => 'baringo  north'),
            array('id' => '159','county_id' => '47','sub_county_name' => 'baringo central'),
            array('id' => '160','county_id' => '47','sub_county_name' => 'baringo south'),
            array('id' => '161','county_id' => '47','sub_county_name' => 'mogotio'),
            array('id' => '162','county_id' => '47','sub_county_name' => 'eldama ravine'),
            array('id' => '163','county_id' => '21','sub_county_name' => 'laikipia west'),
            array('id' => '164','county_id' => '21','sub_county_name' => 'laikipia east'),
            array('id' => '165','county_id' => '21','sub_county_name' => 'laikipia north'),
            array('id' => '166','county_id' => '30','sub_county_name' => 'molo'),
            array('id' => '167','county_id' => '30','sub_county_name' => 'njoro'),
            array('id' => '168','county_id' => '30','sub_county_name' => 'naivasha'),
            array('id' => '169','county_id' => '30','sub_county_name' => 'gilgil'),
            array('id' => '170','county_id' => '30','sub_county_name' => 'kuresoi south'),
            array('id' => '171','county_id' => '30','sub_county_name' => 'kuresoi north'),
            array('id' => '172','county_id' => '30','sub_county_name' => 'subukia'),
            array('id' => '173','county_id' => '30','sub_county_name' => 'rongai'),
            array('id' => '174','county_id' => '30','sub_county_name' => 'bahati'),
            array('id' => '175','county_id' => '30','sub_county_name' => 'nakuru town west'),
            array('id' => '176','county_id' => '30','sub_county_name' => 'nakuru town east'),
            array('id' => '177','county_id' => '32','sub_county_name' => 'kilgoris'),
            array('id' => '178','county_id' => '32','sub_county_name' => 'emurua dikirr'),
            array('id' => '179','county_id' => '32','sub_county_name' => 'narok north'),
            array('id' => '180','county_id' => '32','sub_county_name' => 'narok east'),
            array('id' => '181','county_id' => '32','sub_county_name' => 'narok south'),
            array('id' => '182','county_id' => '32','sub_county_name' => 'narok west'),
            array('id' => '183','county_id' => '12','sub_county_name' => 'kajiado north'),
            array('id' => '184','county_id' => '12','sub_county_name' => 'kajiado central'),
            array('id' => '185','county_id' => '12','sub_county_name' => 'kajiado east'),
            array('id' => '186','county_id' => '12','sub_county_name' => 'kajiado west'),
            array('id' => '187','county_id' => '12','sub_county_name' => 'kajiado south'),
            array('id' => '188','county_id' => '14','sub_county_name' => 'kipkelion east'),
            array('id' => '189','county_id' => '14','sub_county_name' => 'kipkelion west'),
            array('id' => '190','county_id' => '14','sub_county_name' => 'ainamoi'),
            array('id' => '191','county_id' => '14','sub_county_name' => 'bureti'),
            array('id' => '192','county_id' => '14','sub_county_name' => 'belgut'),
            array('id' => '193','county_id' => '14','sub_county_name' => 'sigowet/soin'),
            array('id' => '194','county_id' => '4','sub_county_name' => 'sotik'),
            array('id' => '195','county_id' => '4','sub_county_name' => 'chepalungu'),
            array('id' => '196','county_id' => '4','sub_county_name' => 'bomet east'),
            array('id' => '197','county_id' => '4','sub_county_name' => 'bomet central'),
            array('id' => '198','county_id' => '4','sub_county_name' => 'konoin'),
            array('id' => '199','county_id' => '13','sub_county_name' => 'lugari'),
            array('id' => '200','county_id' => '13','sub_county_name' => 'likuyani'),
            array('id' => '201','county_id' => '13','sub_county_name' => 'malava'),
            array('id' => '202','county_id' => '13','sub_county_name' => 'lurambi'),
            array('id' => '203','county_id' => '13','sub_county_name' => 'navakholo'),
            array('id' => '204','county_id' => '13','sub_county_name' => 'mumias west'),
            array('id' => '205','county_id' => '13','sub_county_name' => 'mumias east'),
            array('id' => '206','county_id' => '13','sub_county_name' => 'matungu'),
            array('id' => '207','county_id' => '13','sub_county_name' => 'butere'),
            array('id' => '208','county_id' => '13','sub_county_name' => 'khwisero'),
            array('id' => '209','county_id' => '13','sub_county_name' => 'shinyalu'),
            array('id' => '210','county_id' => '13','sub_county_name' => 'ikolomani'),
            array('id' => '211','county_id' => '44','sub_county_name' => 'vihiga'),
            array('id' => '212','county_id' => '44','sub_county_name' => 'sabatia'),
            array('id' => '213','county_id' => '44','sub_county_name' => 'hamisi'),
            array('id' => '214','county_id' => '44','sub_county_name' => 'luanda'),
            array('id' => '215','county_id' => '44','sub_county_name' => 'emuhaya'),
            array('id' => '216','county_id' => '5','sub_county_name' => 'mt.elgon'),
            array('id' => '217','county_id' => '5','sub_county_name' => 'sirisia'),
            array('id' => '218','county_id' => '5','sub_county_name' => 'kabuchai'),
            array('id' => '219','county_id' => '5','sub_county_name' => 'bumula'),
            array('id' => '220','county_id' => '5','sub_county_name' => 'kanduyi'),
            array('id' => '221','county_id' => '5','sub_county_name' => 'webuye east'),
            array('id' => '222','county_id' => '5','sub_county_name' => 'webuye west'),
            array('id' => '223','county_id' => '5','sub_county_name' => 'kimilili'),
            array('id' => '224','county_id' => '5','sub_county_name' => 'tongaren'),
            array('id' => '225','county_id' => '6','sub_county_name' => 'teso north'),
            array('id' => '226','county_id' => '6','sub_county_name' => 'teso south'),
            array('id' => '227','county_id' => '6','sub_county_name' => 'nambale'),
            array('id' => '228','county_id' => '6','sub_county_name' => 'matayos'),
            array('id' => '229','county_id' => '6','sub_county_name' => 'butula'),
            array('id' => '230','county_id' => '6','sub_county_name' => 'funyula'),
            array('id' => '231','county_id' => '6','sub_county_name' => 'budalangi'),
            array('id' => '232','county_id' => '37','sub_county_name' => 'ugenya'),
            array('id' => '233','county_id' => '37','sub_county_name' => 'ugunja'),
            array('id' => '234','county_id' => '37','sub_county_name' => 'alego usonga'),
            array('id' => '235','county_id' => '37','sub_county_name' => 'gem'),
            array('id' => '236','county_id' => '37','sub_county_name' => 'bondo'),
            array('id' => '237','county_id' => '37','sub_county_name' => 'rarieda'),
            array('id' => '238','county_id' => '3','sub_county_name' => 'kisumu east'),
            array('id' => '239','county_id' => '3','sub_county_name' => 'kisumu west'),
            array('id' => '240','county_id' => '3','sub_county_name' => 'kisumu central'),
            array('id' => '241','county_id' => '3','sub_county_name' => 'seme'),
            array('id' => '242','county_id' => '3','sub_county_name' => 'nyando'),
            array('id' => '243','county_id' => '3','sub_county_name' => 'muhoroni'),
            array('id' => '244','county_id' => '3','sub_county_name' => 'nyakach'),
            array('id' => '245','county_id' => '10','sub_county_name' => 'kasipul'),
            array('id' => '246','county_id' => '10','sub_county_name' => 'kabondo kasipul'),
            array('id' => '247','county_id' => '10','sub_county_name' => 'karachuonyo'),
            array('id' => '248','county_id' => '10','sub_county_name' => 'rangwe'),
            array('id' => '249','county_id' => '10','sub_county_name' => 'homa bay town'),
            array('id' => '250','county_id' => '10','sub_county_name' => 'ndhiwa'),
            array('id' => '251','county_id' => '10','sub_county_name' => 'mbita'),
            array('id' => '252','county_id' => '10','sub_county_name' => 'suba'),
            array('id' => '253','county_id' => '27','sub_county_name' => 'rongo'),
            array('id' => '254','county_id' => '27','sub_county_name' => 'awendo'),
            array('id' => '255','county_id' => '27','sub_county_name' => 'suna east'),
            array('id' => '256','county_id' => '27','sub_county_name' => 'suna west'),
            array('id' => '257','county_id' => '27','sub_county_name' => 'uriri'),
            array('id' => '258','county_id' => '27','sub_county_name' => 'nyatike'),
            array('id' => '259','county_id' => '27','sub_county_name' => 'kuria west'),
            array('id' => '260','county_id' => '27','sub_county_name' => 'kuria east'),
            array('id' => '261','county_id' => '18','sub_county_name' => 'bonchari'),
            array('id' => '262','county_id' => '18','sub_county_name' => 'south mugirango'),
            array('id' => '263','county_id' => '18','sub_county_name' => 'bomachoge borabu'),
            array('id' => '264','county_id' => '18','sub_county_name' => 'bobasi'),
            array('id' => '265','county_id' => '18','sub_county_name' => 'bomachoge chache'),
            array('id' => '266','county_id' => '18','sub_county_name' => 'nyaribari masaba'),
            array('id' => '267','county_id' => '18','sub_county_name' => 'nyaribari chache'),
            array('id' => '268','county_id' => '18','sub_county_name' => 'kitutu chache north'),
            array('id' => '269','county_id' => '18','sub_county_name' => 'kitutu chache south'),
            array('id' => '270','county_id' => '33','sub_county_name' => 'kitutu masaba'),
            array('id' => '271','county_id' => '33','sub_county_name' => 'west mugirango'),
            array('id' => '272','county_id' => '33','sub_county_name' => 'north mugirango'),
            array('id' => '273','county_id' => '33','sub_county_name' => 'borabu'),
            array('id' => '274','county_id' => '1','sub_county_name' => 'westlands'),
            array('id' => '275','county_id' => '1','sub_county_name' => 'dagoretti north'),
            array('id' => '276','county_id' => '1','sub_county_name' => 'dagoretti south'),
            array('id' => '277','county_id' => '1','sub_county_name' => 'langata'),
            array('id' => '278','county_id' => '1','sub_county_name' => 'kibra'),
            array('id' => '279','county_id' => '1','sub_county_name' => 'roysambu'),
            array('id' => '280','county_id' => '1','sub_county_name' => 'kasarani'),
            array('id' => '281','county_id' => '1','sub_county_name' => 'ruaraka'),
            array('id' => '282','county_id' => '1','sub_county_name' => 'embakasi south'),
            array('id' => '283','county_id' => '1','sub_county_name' => 'embakasi north'),
            array('id' => '284','county_id' => '1','sub_county_name' => 'embakasi central'),
            array('id' => '285','county_id' => '1','sub_county_name' => 'embakasi east'),
            array('id' => '286','county_id' => '1','sub_county_name' => 'embakasi west'),
            array('id' => '287','county_id' => '1','sub_county_name' => 'makadara'),
            array('id' => '288','county_id' => '1','sub_county_name' => 'kamukunji'),
            array('id' => '289','county_id' => '1','sub_county_name' => 'starehe'),
            array('id' => '290','county_id' => '1','sub_county_name' => 'mathare')
        ));
    }
}
